title: "Mi Sitio Jekyll"
description: "Una descripci칩n de mi sitio Jekyll"
baseurl: "index.html" # la URL base de tu sitio, por ejemplo, /blog
url: "https://kenshinwinter.github.io/Proyecto-Service-Japon/index.html" # la URL completa de tu sitio
theme: minima # el tema que est치s usando
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Configuraci칩n de Sass
sass:
  sass_dir: _sass
  style: compressed

# Configuraci칩n de Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: "plaintext"
